### ISSUE TITLE
Wrapper for grdimage

### ISSUE THREAD

**Issue by El-minadero** [GenericMappingTools/gmt-python#124]
Hey everyone. I'm trying to overlay/add terrain detail on a map, and not having much bash, C, jupyter notebook, or c family language experience, attempting to add a hillshade map has been difficult. 

I've got a fair bit of experience with python projects collaboration and OOP stuff, and Id be willing to help implement this feature, but of course the C side stuff is very foreign to me.

**Comment by leouieda** [comment]
Hi @El-minadero, thanks for writing and offering to help! Sorry for the late reply.

There is still a piece of infrastructure missing from `LibGMT` to make the grd modules work: passing netCDF style grids to GMT throught the virtual file machinery. This isn't a huge a problem and I'm hopping to have it done within the next 2 weeks. I just haven't had time to implement it yet.

Once that is done, we can work on wrapping the `grdimage` module and I'd love help with that. It will probably look very similar to something like the wrapper for `plot`: https://github.com/GenericMappingTools/gmt-python/blob/master/gmt/base_plotting.py#L195

Since GMT uses netCDF grids, I'm thinking of having xarray.Dataset  as our "official" grid format. We can't use plain numpy arrays most of the time because there are no coordinates attached (and we need those). It would also make it easy to load netCDF data and pass it directly to `fig.grdimage`, for example.

The hillshading in GMT6 is a lot easier. You can get a hillshaded map with a single option (`-I`).

I'll ping back here when I have the xarray support working and we can discuss adding `grdimage` if you're still up for it.

**Comment by adamnicholasprice** [comment]
I second this feature request!

**Comment by leouieda** [comment]
@adamnicholasprice thanks for the feedback! I'll update this issue when the required infrastructure is in place.

**Comment by leouieda** [comment]
Quick update on this issue, now that #159 is merged we can start wrapping the grid plotting modules. 

@El-minadero if you want to take a stab at wrapping grdimage let me know. Look at the [docs for `LibGMT.grid_to_vfile`](www.gmtpython.xyz/api/gmt.clib.LibGMT.html) for an example of how to pass in the grid object to a GMT module.

**Comment by seisman** [comment]
@El-minadero @adamnicholasprice @leouieda I'd like to help implement it if no one is working on this issue.

**Comment by leouieda** [comment]
@seisman I'm working out some kinks still on the API to get this working. We found a few bugs in GMT related to grids because this part of the API was never exercised. I'm hoping to have it done tomorrow.
