### ISSUE TITLE
add the base map from google maps

### ISSUE THREAD

**Issue by rezamn** [GenericMappingTools/gmt-python#95]
Dear all
I think of if you could add a command that download the basemap using google maps, srtm etc directly from internet.
Best regards

**Comment by leouieda** [comment]
Hi @rezamn, thanks for the feedback! The google maps data is tricky because it's not open-source. So we can't use it. But there are plans to use coastline data from open street map in GMT. That will take some time because it would require some big changes in GMT.

The SRTM data is something that already works in GMT6. I haven't ported that to Python yet but it will be coming soon.
